# Generated by Django 2.2 on 2021-09-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='City',
            field=models.ForeignKey(default=1, on_delete=False, to='product.City'),
        ),
        migrations.AddField(
            model_name='place',
            name='Description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='Name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
