# Generated by Django 2.2 on 2021-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210925_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='url',
        ),
        migrations.AddField(
            model_name='img',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
