# Generated by Django 2.2 on 2021-09-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Type',
            field=models.IntegerField(default=1),
        ),
    ]
