# Generated by Django 2.2 on 2021-09-26 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210926_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='./icon-login.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 26, 20, 15, 0, 294791)),
        ),
    ]
