# Generated by Django 2.2 on 2021-09-26 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210926_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 26, 20, 48, 2, 779668)),
        ),
    ]
