# Generated by Django 2.2 on 2021-09-26 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210926_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 26, 21, 19, 29, 923241)),
        ),
    ]
