# Generated by Django 2.2 on 2021-09-27 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210926_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Site',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Tel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 27, 16, 27, 21, 913033)),
        ),
    ]
